export const brands = [
  "ABSOLUT", "AC_DC", "ADIDAS", "ADVIL", "AKAI PROFESSIONAL", "ALF",
  "ALIEN WORKSHOP", "APPLE", "ARBY'S", "ART ATTACK", "ASICS", "ATARI",
  "ATLANTA HAWKS", "ATLANTIC RECORDS", "BARBIE", "BEATS BY DRE", "BEHRINGER",
  "BELL'S", "BEN & JERRY'S", "BERGHAUS", "BIC", "BLACK SABBATH", "BLAUPUNKT",
  "BLOCKBUSTER", "BRAT", "BUBBALICIOUS", "BUPA", "BURGER KING",
  "CABBAGE PATCH KIDS", "CANADA DRY", "CANON", "CAP'N'CRUNCH",
  "CAPTAIN PLANET", "CARHARTT", "CARLSBERG", "CARTOON NETWORK", "CASTROL",
  "CHAMPION", "CHEERS", "CHICAGO BULLS", "CHIPS AHOY", "CHIQUITA",
  "CHUPA CHUPS", "CNN", "COCA-COLA", "CORONA EXTRA", "COSTCO",
  "COUNT DUCKULA", "CRACKER BARREL", "CRUNCH", "D.A.R.E", "DANGER MOUSE",
  "DANZIG", "DEL MONTE", "DENNY'S", "DHL", "DICKHOUSE", "DICKIES", "DOLE",
  "DORITOS CLASSIC", "DUCATI", "DUCATI CLASSIC", "DUNKIN DONUTS", "DUPLO",
  "EBAY", "ELLESSE", "ERNIE BALL", "ESPN", "ESSO", "EVIAN", "FAIRY",
  "FENDER", "FILA", "FISCHER-PRICE", "FJALLRAVEN", "FORD", "FORTNITE",
  "FRIENDS", "FRUIT LOOPS", "FRUIT OF THE LOOM", "GARBAGE PAIL KIDS",
  "GIRL", "GOODYEAR", "GOOGLE", "GULF", "HARIBO (WHITE)", "HAVANA CLUB",
  "HEINZ", "HILTI", "HOT WHEELS", "HUBBA BUBBA", "IHOP", "IKEA",
  "IN-N-OUT BURGER", "JELLY BEAN", "JIM BEAN", "JOSE CUERVO",
  "JURASSIC PARK", "KAPPA", "KELLOGG'S", "KFC", "KIT KAT", "KODAK",
  "KONAMI", "KRISPY KREME", "KRONENBOURG", "LAY'S", "LEFFE", "LEGO",
  "LEICA", "LEVI'S", "LIFE", "LONDON UNDERGROUND", "LUCKY CHARMS",
  "LUCKY STRIKE", "MALIBU", "MARLBORO", "MARS", "MARVEL", "MASK",
  "MASTERS OF THE UNIVERSE", "MATCHBOX", "MATTEL", "MCDONALD'S",
  "METALLICA", "MICRO MACHINES", "MILKA", "MILKY WAY", "MOBIL", "MONOPOLY",
  "MOUNTAIN DEW", "NASA", "NASA (2)", "NERDS", "NERF", "NESQUIK", "NETFLIX",
  "NEW BALANCE", "NHS", "NICKELODEAN", "NIKE", "NINTENDO", "NIRVANA",
  "NUTELLA", "NWA", "OBEY", "ODD FUTURE", "OLD EL PASO", "ORANGE",
  "OREO'S", "PATAGONIA", "PBS", "PEPSI", "PERRIER", "PEZ", "PIZZA HUT",
  "PLAYSTATION", "POLAROID", "PRADA", "PRINGLES", "PUBLIC ENEMY", "PUMA",
  "QUAKER", "RAISING CANE'S", "RED BULL", "REESE'S", "ROBOCOP", "RUGRATS",
  "RUN DMC", "SANTA CRUZ", "SAVED BY THE BELL", "SCHWEPPES", "SEGA",
  "SEINFELD", "SESAME STREET", "SEVEN ELEVEN", "SINCLAIR", "SKITTLES",
  "SNAPPLE", "SNICKERS", "SOUNDCLOUD", "SPAR", "SPRITE", "STARBUCKS",
  "STELLA ARTOIS", "STONE ISLAND", "STRANGER THINGS", "SUB POP", "SUBWAY",
  "SUPER MARIO", "SUPER NINTENDO", "SUPREME", "TACO BELL", "TAG HEUR",
  "TED", "TEENAGE MUTANT NINJA TURTLES", "TEMU", "TESCO",
  "THE FRESH PRINCE OF BEL-AIR", "THE MASK", "THE MUNCH BUNCH",
  "THE NORTH FACE", "THE REAL GHOSTBUSTERS", "THE SIMPSONS", "THE SMURFS",
  "THRASHER", "TIC TAC", "TIDE", "TIKTOK", "TINDER", "TOMMY BOY",
  "TONY'S CHOCOLONEY", "TOY MACHINE", "TRANSFORMERS", "TRON",
  "TROPICAL SUN", "TV-AM", "TWITCH", "TWIX", "UPS", "WAFFLE HOUSE",
  "WARNER BROS", "WENDY'S", "WHOLE FOODS", "WILSON", "WRIGLEY'S DOUBLEMINT",
  "YAHOO!", "YONEX", "YUBO"
];

export function normalize(str) {
  return str.toUpperCase().replace(/[^A-Z0-9 ]/g, "").replace(/\s+/g, " ").trim();
}

export function checkAnswer(input, brand) {
  const normInput = normalize(input);
  const normBrand = normalize(brand);
  return normInput === normBrand;
}

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
